version: "3.8"
services:
  database:
    container_name: incident-training-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - $PWD/docker/db/data:/var/lib/postgresql/data
  server:
    container_name: incident-training
    command: "sh ./run.sh" # Override for DEV
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
